declare -a links=(
	"https://suitesparse-collection-website.herokuapp.com/MM/Janna/Transport.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/VLSI/vas_stokes_4M.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/VLSI/vas_stokes_1M.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/VLSI/vas_stokes_2M.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/VLSI/ss.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/Janna/Queen_4147.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/Janna/PFlow_742.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/Janna/Cube_Coup_dt0.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/Janna/Cube_Coup_dt6.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/Janna/Long_Coup_dt6.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/Janna/StocF-1465.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/VLSI/nv2.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/VLSI/power9.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/VLSI/test1.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/VLSI/imagesensor.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/VLSI/mosfet2.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/VLSI/dgreen.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/VLSI/radiation.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/VLSI/nv1.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/Janna/ML_Laplace.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/VLSI/stokes.tar.gz"
	# "https://suitesparse-collection-website.herokuapp.com/MM/Janna/Hook_1498.tar.gz
    # "https://suitesparse-collection-website.herokuapp.com/MM/Schmid/thermal2.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/GHS_psdef/crankseg_1.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Boeing/pwtk.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Rajat/rajat31.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Dziekonski/gsm_106857.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Koutsovasilis/F1.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/vanHeukelum/cage14.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Janna/Fault_639.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/GHS_psdef/inline_1.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Janna/Emilia_923.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/GHS_psdef/ldoor.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Schenk_AFE/af_shell10.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Janna/Hook_1498.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Janna/Geo_1438.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Janna/Serena.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Oberwolfach/bone010.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/GHS_psdef/audikw_1.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/channel-500x100x100-b050.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Dziekonski/dielFilterV3real.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Schenk/nlpkkt120.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Janna/ML_Geer.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Janna/Flan_1565.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Schenk/nlpkkt200.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n24.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Mazaheri/bundle_adj.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Zaoui/kkt_power.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/road_usa.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/LAW/hollywood-2009.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Williams/webbase-1M.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Rothberg/gearbox.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Fluorem/RM07R.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Schenk/nlpkkt240.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Janna/Queen_4147.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/VLSI/stokes.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Fluorem/HV15R.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/VLSI/vas_stokes_4M.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Janna/Bump_2911.tar.gz"
    # "https://suitesparse-collection-website.herokuapp.com/MM/Janna/Long_Coup_dt0.tar.gz"
)


for link in "${links[@]}";
do
    wget $link
    tar_ball="${link##*/}"
    tar -xvzf $tar_ball
    matrix_name="${tar_ball%%.*}"
    cp $matrix_name/* $PWD && rm -rf $tar_ball && rm -rf $matrix_name
done
